### ISSUE TITLE
인코딩 오류

### ISSUE THREAD

**Issue by project-dy** [pdpdds/PrettyOS#1]
~~[build.sh](https://github.com/pdpdds/PrettyOS/blob/main/build.sh#L3)만 봐도 인코딩이 깨진것 같다는 것을 한눈에 느낄실수 있습니다.
문서도 많이 깨졌네요.
.git폴더 내부에 있는 config파일에서 인코딩 설정을 확인해주세요.~~

수정
제작하신게 아니라 포팅하신건줄 몰랐습니다.
한국어로 쓰여있는게 깨진줄 알았으나 말씀하신데로 홈페이지 들어가보는 등 조금더 검색해보니 포팅인걸 알게되었습니다.
잘못된 이슈를 열어 죄송합니다.
앞으로는 더욱 확인하고 이슈를 열겠습니다.
죄송합니다.

**Comment by pdpdds** [comment]
빌드 방법을 읽으세요. 아니면 PrettyOS 홈페이지를 방문해서 해당 소스코드로 빌드하세요.
